version: '3.7'

services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
#    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ''
      ME_CONFIG_MONGODB_URL: mongodb://192.168.88.17:27017
#      ME_CONFIG_MONGODB_SERVER: 192.168.88.17
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: aurick
#      ME_CONFIG_MONGODB_ADMINPASSWORD: aurick
    networks:
      - mongo-express

networks:
  mongo-express: