version: '3.7'

services:
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # volumes:
      # - ~/data:/data/db
    networks:
      mongodb-network:
        aliases:
          - mongodb-host
          
  mongo-express:
    image: mongo-express:0.49.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-host
      - ME_CONFIG_MONGODB_PORT=27017
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - mongodb-network
    depends_on:
      - mongodb

networks:
  mongodb-network: